// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api/envoy/config/filter/http/nats/streaming/v2/nats_streaming.proto

package v2

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [#proto-status: experimental]
type NatsStreaming struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cluster        string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	MaxConnections uint32                 `protobuf:"varint,2,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	OpTimeout      *durationpb.Duration   `protobuf:"bytes,3,opt,name=op_timeout,json=opTimeout,proto3" json:"op_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NatsStreaming) Reset() {
	*x = NatsStreaming{}
	mi := &file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatsStreaming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsStreaming) ProtoMessage() {}

func (x *NatsStreaming) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsStreaming.ProtoReflect.Descriptor instead.
func (*NatsStreaming) Descriptor() ([]byte, []int) {
	return file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *NatsStreaming) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *NatsStreaming) GetMaxConnections() uint32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *NatsStreaming) GetOpTimeout() *durationpb.Duration {
	if x != nil {
		return x.OpTimeout
	}
	return nil
}

type NatsStreamingPerRoute struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Subject        string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	ClusterId      string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	DiscoverPrefix string                 `protobuf:"bytes,3,opt,name=discover_prefix,json=discoverPrefix,proto3" json:"discover_prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NatsStreamingPerRoute) Reset() {
	*x = NatsStreamingPerRoute{}
	mi := &file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatsStreamingPerRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsStreamingPerRoute) ProtoMessage() {}

func (x *NatsStreamingPerRoute) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsStreamingPerRoute.ProtoReflect.Descriptor instead.
func (*NatsStreamingPerRoute) Descriptor() ([]byte, []int) {
	return file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *NatsStreamingPerRoute) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NatsStreamingPerRoute) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NatsStreamingPerRoute) GetDiscoverPrefix() string {
	if x != nil {
		return x.DiscoverPrefix
	}
	return ""
}

var File_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto protoreflect.FileDescriptor

const file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDesc = "" +
	"\n" +
	"Capi/envoy/config/filter/http/nats/streaming/v2/nats_streaming.proto\x12*envoy.config.filter.http.nats.streaming.v2\x1a\x1egoogle/protobuf/duration.proto\x1a\x17validate/validate.proto\"\x95\x01\n" +
	"\rNatsStreaming\x12!\n" +
	"\acluster\x18\x01 \x01(\tB\a\xfaB\x04r\x02 \x01R\acluster\x12'\n" +
	"\x0fmax_connections\x18\x02 \x01(\rR\x0emaxConnections\x128\n" +
	"\n" +
	"op_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\topTimeout\"\x94\x01\n" +
	"\x15NatsStreamingPerRoute\x12!\n" +
	"\asubject\x18\x01 \x01(\tB\a\xfaB\x04r\x02 \x01R\asubject\x12&\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02 \x01R\tclusterId\x120\n" +
	"\x0fdiscover_prefix\x18\x03 \x01(\tB\a\xfaB\x04r\x02 \x01R\x0ediscoverPrefixB\x9a\x01\n" +
	"8io.envoyproxy.envoy.config.filter.http.nats.streaming.v2B\x12NatsStreamingProtoP\x01ZHgithub.com/solo-io/envoy-gloo/go/config/filter/http/nats/streaming/v2;v2b\x06proto3"

var (
	file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDescOnce sync.Once
	file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDescData []byte
)

func file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDescGZIP() []byte {
	file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDescOnce.Do(func() {
		file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDesc), len(file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDesc)))
	})
	return file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDescData
}

var file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_goTypes = []any{
	(*NatsStreaming)(nil),         // 0: envoy.config.filter.http.nats.streaming.v2.NatsStreaming
	(*NatsStreamingPerRoute)(nil), // 1: envoy.config.filter.http.nats.streaming.v2.NatsStreamingPerRoute
	(*durationpb.Duration)(nil),   // 2: google.protobuf.Duration
}
var file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_depIdxs = []int32{
	2, // 0: envoy.config.filter.http.nats.streaming.v2.NatsStreaming.op_timeout:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_init() }
func file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_init() {
	if File_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDesc), len(file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_goTypes,
		DependencyIndexes: file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_depIdxs,
		MessageInfos:      file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_msgTypes,
	}.Build()
	File_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto = out.File
	file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_goTypes = nil
	file_api_envoy_config_filter_http_nats_streaming_v2_nats_streaming_proto_depIdxs = nil
}
