//go:build !disable_pgv
// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/envoy/config/filter/http/nats/streaming/v2/nats_streaming.proto

package v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NatsStreaming with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NatsStreaming) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NatsStreaming with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NatsStreamingMultiError, or
// nil if none found.
func (m *NatsStreaming) ValidateAll() error {
	return m.validate(true)
}

func (m *NatsStreaming) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetCluster()) < 1 {
		err := NatsStreamingValidationError{
			field:  "Cluster",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for MaxConnections

	if all {
		switch v := interface{}(m.GetOpTimeout()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NatsStreamingValidationError{
					field:  "OpTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NatsStreamingValidationError{
					field:  "OpTimeout",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOpTimeout()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NatsStreamingValidationError{
				field:  "OpTimeout",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return NatsStreamingMultiError(errors)
	}

	return nil
}

// NatsStreamingMultiError is an error wrapping multiple validation errors
// returned by NatsStreaming.ValidateAll() if the designated constraints
// aren't met.
type NatsStreamingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NatsStreamingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NatsStreamingMultiError) AllErrors() []error { return m }

// NatsStreamingValidationError is the validation error returned by
// NatsStreaming.Validate if the designated constraints aren't met.
type NatsStreamingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NatsStreamingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NatsStreamingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NatsStreamingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NatsStreamingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NatsStreamingValidationError) ErrorName() string { return "NatsStreamingValidationError" }

// Error satisfies the builtin error interface
func (e NatsStreamingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNatsStreaming.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NatsStreamingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NatsStreamingValidationError{}

// Validate checks the field values on NatsStreamingPerRoute with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NatsStreamingPerRoute) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NatsStreamingPerRoute with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NatsStreamingPerRouteMultiError, or nil if none found.
func (m *NatsStreamingPerRoute) ValidateAll() error {
	return m.validate(true)
}

func (m *NatsStreamingPerRoute) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetSubject()) < 1 {
		err := NatsStreamingPerRouteValidationError{
			field:  "Subject",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetClusterId()) < 1 {
		err := NatsStreamingPerRouteValidationError{
			field:  "ClusterId",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetDiscoverPrefix()) < 1 {
		err := NatsStreamingPerRouteValidationError{
			field:  "DiscoverPrefix",
			reason: "value length must be at least 1 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return NatsStreamingPerRouteMultiError(errors)
	}

	return nil
}

// NatsStreamingPerRouteMultiError is an error wrapping multiple validation
// errors returned by NatsStreamingPerRoute.ValidateAll() if the designated
// constraints aren't met.
type NatsStreamingPerRouteMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NatsStreamingPerRouteMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NatsStreamingPerRouteMultiError) AllErrors() []error { return m }

// NatsStreamingPerRouteValidationError is the validation error returned by
// NatsStreamingPerRoute.Validate if the designated constraints aren't met.
type NatsStreamingPerRouteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NatsStreamingPerRouteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NatsStreamingPerRouteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NatsStreamingPerRouteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NatsStreamingPerRouteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NatsStreamingPerRouteValidationError) ErrorName() string {
	return "NatsStreamingPerRouteValidationError"
}

// Error satisfies the builtin error interface
func (e NatsStreamingPerRouteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNatsStreamingPerRoute.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NatsStreamingPerRouteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NatsStreamingPerRouteValidationError{}
