// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/envoy/config/filter/http/nats/streaming/v2/payload.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Payload) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_api_envoy_config_filter_http_nats_streaming_v2_payload_proto protoreflect.FileDescriptor

const file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDesc = "" +
	"\n" +
	"<api/envoy/config/filter/http/nats/streaming/v2/payload.proto\x12\x02pb\"\x8d\x01\n" +
	"\aPayload\x122\n" +
	"\aheaders\x18\x01 \x03(\v2\x18.pb.Payload.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01Bl\n" +
	"\x10io.envoyproxy.pbB\fPayloadProtoP\x01ZHgithub.com/solo-io/envoy-gloo/go/config/filter/http/nats/streaming/v2;v2b\x06proto3"

var (
	file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDescOnce sync.Once
	file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDescData []byte
)

func file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDescGZIP() []byte {
	file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDescOnce.Do(func() {
		file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDesc), len(file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDesc)))
	})
	return file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDescData
}

var file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_goTypes = []any{
	(*Payload)(nil), // 0: pb.Payload
	nil,             // 1: pb.Payload.HeadersEntry
}
var file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_depIdxs = []int32{
	1, // 0: pb.Payload.headers:type_name -> pb.Payload.HeadersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_init() }
func file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_init() {
	if File_api_envoy_config_filter_http_nats_streaming_v2_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDesc), len(file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_goTypes,
		DependencyIndexes: file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_depIdxs,
		MessageInfos:      file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_msgTypes,
	}.Build()
	File_api_envoy_config_filter_http_nats_streaming_v2_payload_proto = out.File
	file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_goTypes = nil
	file_api_envoy_config_filter_http_nats_streaming_v2_payload_proto_depIdxs = nil
}
