//go:build !disable_pgv
// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/envoy/config/filter/http/upstream_wait/v2/upstream_wait_filter.proto

package v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpstreamWaitFilterConfig with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpstreamWaitFilterConfig) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpstreamWaitFilterConfig with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpstreamWaitFilterConfigMultiError, or nil if none found.
func (m *UpstreamWaitFilterConfig) ValidateAll() error {
	return m.validate(true)
}

func (m *UpstreamWaitFilterConfig) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpstreamWaitFilterConfigMultiError(errors)
	}

	return nil
}

// UpstreamWaitFilterConfigMultiError is an error wrapping multiple validation
// errors returned by UpstreamWaitFilterConfig.ValidateAll() if the designated
// constraints aren't met.
type UpstreamWaitFilterConfigMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpstreamWaitFilterConfigMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpstreamWaitFilterConfigMultiError) AllErrors() []error { return m }

// UpstreamWaitFilterConfigValidationError is the validation error returned by
// UpstreamWaitFilterConfig.Validate if the designated constraints aren't met.
type UpstreamWaitFilterConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpstreamWaitFilterConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpstreamWaitFilterConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpstreamWaitFilterConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpstreamWaitFilterConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpstreamWaitFilterConfigValidationError) ErrorName() string {
	return "UpstreamWaitFilterConfigValidationError"
}

// Error satisfies the builtin error interface
func (e UpstreamWaitFilterConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpstreamWaitFilterConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpstreamWaitFilterConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpstreamWaitFilterConfigValidationError{}
