// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: api/envoy/type/streaming/protocol.proto

package streaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for start position type.
type StartPosition int32

const (
	StartPosition_NewOnly        StartPosition = 0
	StartPosition_LastReceived   StartPosition = 1
	StartPosition_TimeDeltaStart StartPosition = 2
	StartPosition_SequenceStart  StartPosition = 3
	StartPosition_First          StartPosition = 4
)

// Enum value maps for StartPosition.
var (
	StartPosition_name = map[int32]string{
		0: "NewOnly",
		1: "LastReceived",
		2: "TimeDeltaStart",
		3: "SequenceStart",
		4: "First",
	}
	StartPosition_value = map[string]int32{
		"NewOnly":        0,
		"LastReceived":   1,
		"TimeDeltaStart": 2,
		"SequenceStart":  3,
		"First":          4,
	}
)

func (x StartPosition) Enum() *StartPosition {
	p := new(StartPosition)
	*p = x
	return p
}

func (x StartPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_api_envoy_type_streaming_protocol_proto_enumTypes[0].Descriptor()
}

func (StartPosition) Type() protoreflect.EnumType {
	return &file_api_envoy_type_streaming_protocol_proto_enumTypes[0]
}

func (x StartPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartPosition.Descriptor instead.
func (StartPosition) EnumDescriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{0}
}

// How messages are delivered to the STAN cluster
type PubMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"` // ClientID
	Guid          string                 `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`         // guid
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`   // subject
	Reply         string                 `protobuf:"bytes,4,opt,name=reply,proto3" json:"reply,omitempty"`       // optional reply
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`         // payload
	Sha256        []byte                 `protobuf:"bytes,10,opt,name=sha256,proto3" json:"sha256,omitempty"`    // optional sha256 of data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubMsg) Reset() {
	*x = PubMsg{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubMsg) ProtoMessage() {}

func (x *PubMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubMsg.ProtoReflect.Descriptor instead.
func (*PubMsg) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *PubMsg) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *PubMsg) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *PubMsg) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PubMsg) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *PubMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PubMsg) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// Used to ACK to publishers
type PubAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`   // guid
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // err string, empty/omitted if no error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubAck) Reset() {
	*x = PubAck{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubAck) ProtoMessage() {}

func (x *PubAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubAck.ProtoReflect.Descriptor instead.
func (*PubAck) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *PubAck) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *PubAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Msg struct. Sequence is assigned for global ordering by
// the cluster after the publisher has been acknowledged.
type MsgProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`       // globally ordered sequence number for the subject's channel
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`          // subject
	Reply         string                 `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`              // optional reply
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                // payload
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`     // received timestamp
	Redelivered   bool                   `protobuf:"varint,6,opt,name=redelivered,proto3" json:"redelivered,omitempty"` // Flag specifying if the message is being redelivered
	CRC32         uint32                 `protobuf:"varint,10,opt,name=CRC32,proto3" json:"CRC32,omitempty"`            // optional IEEE CRC32
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgProto) Reset() {
	*x = MsgProto{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgProto) ProtoMessage() {}

func (x *MsgProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgProto.ProtoReflect.Descriptor instead.
func (*MsgProto) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *MsgProto) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MsgProto) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MsgProto) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *MsgProto) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MsgProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MsgProto) GetRedelivered() bool {
	if x != nil {
		return x.Redelivered
	}
	return false
}

func (x *MsgProto) GetCRC32() uint32 {
	if x != nil {
		return x.CRC32
	}
	return 0
}

// Ack will deliver an ack for a delivered msg.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`    // Subject
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"` // Sequence to acknowledge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Ack) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Connection Request
type ConnectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientID       string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`             // Client name/identifier.
	HeartbeatInbox string                 `protobuf:"bytes,2,opt,name=heartbeatInbox,proto3" json:"heartbeatInbox,omitempty"` // Inbox for server initiated heartbeats.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *ConnectRequest) GetHeartbeatInbox() string {
	if x != nil {
		return x.HeartbeatInbox
	}
	return ""
}

// Response to a client connect
type ConnectResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PubPrefix        string                 `protobuf:"bytes,1,opt,name=pubPrefix,proto3" json:"pubPrefix,omitempty"`               // Prefix to use when publishing to this STAN cluster
	SubRequests      string                 `protobuf:"bytes,2,opt,name=subRequests,proto3" json:"subRequests,omitempty"`           // Subject to use for subscription requests
	UnsubRequests    string                 `protobuf:"bytes,3,opt,name=unsubRequests,proto3" json:"unsubRequests,omitempty"`       // Subject to use for unsubscribe requests
	CloseRequests    string                 `protobuf:"bytes,4,opt,name=closeRequests,proto3" json:"closeRequests,omitempty"`       // Subject for closing the stan connection
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                       // err string, empty/omitted if no error
	SubCloseRequests string                 `protobuf:"bytes,6,opt,name=subCloseRequests,proto3" json:"subCloseRequests,omitempty"` // Subject to use for subscription close requests
	PublicKey        string                 `protobuf:"bytes,100,opt,name=publicKey,proto3" json:"publicKey,omitempty"`             // Possibly used to sign acks, etc.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectResponse) GetPubPrefix() string {
	if x != nil {
		return x.PubPrefix
	}
	return ""
}

func (x *ConnectResponse) GetSubRequests() string {
	if x != nil {
		return x.SubRequests
	}
	return ""
}

func (x *ConnectResponse) GetUnsubRequests() string {
	if x != nil {
		return x.UnsubRequests
	}
	return ""
}

func (x *ConnectResponse) GetCloseRequests() string {
	if x != nil {
		return x.CloseRequests
	}
	return ""
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConnectResponse) GetSubCloseRequests() string {
	if x != nil {
		return x.SubCloseRequests
	}
	return ""
}

func (x *ConnectResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// Protocol for a client to subscribe
type SubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientID       string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`                                   // ClientID
	Subject        string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`                                     // Formal subject to subscribe to, e.g. foo.bar
	QGroup         string                 `protobuf:"bytes,3,opt,name=qGroup,proto3" json:"qGroup,omitempty"`                                       // Optional queue group
	Inbox          string                 `protobuf:"bytes,4,opt,name=inbox,proto3" json:"inbox,omitempty"`                                         // Inbox subject to deliver messages on
	MaxInFlight    int32                  `protobuf:"varint,5,opt,name=maxInFlight,proto3" json:"maxInFlight,omitempty"`                            // Maximum inflight messages without an ack allowed
	AckWaitInSecs  int32                  `protobuf:"varint,6,opt,name=ackWaitInSecs,proto3" json:"ackWaitInSecs,omitempty"`                        // Timeout for receiving an ack from the client
	DurableName    string                 `protobuf:"bytes,7,opt,name=durableName,proto3" json:"durableName,omitempty"`                             // Optional durable name which survives client restarts
	StartPosition  StartPosition          `protobuf:"varint,10,opt,name=startPosition,proto3,enum=pb.StartPosition" json:"startPosition,omitempty"` // Start position
	StartSequence  uint64                 `protobuf:"varint,11,opt,name=startSequence,proto3" json:"startSequence,omitempty"`                       // Optional start sequence number
	StartTimeDelta int64                  `protobuf:"varint,12,opt,name=startTimeDelta,proto3" json:"startTimeDelta,omitempty"`                     // Optional start time
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *SubscriptionRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *SubscriptionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubscriptionRequest) GetQGroup() string {
	if x != nil {
		return x.QGroup
	}
	return ""
}

func (x *SubscriptionRequest) GetInbox() string {
	if x != nil {
		return x.Inbox
	}
	return ""
}

func (x *SubscriptionRequest) GetMaxInFlight() int32 {
	if x != nil {
		return x.MaxInFlight
	}
	return 0
}

func (x *SubscriptionRequest) GetAckWaitInSecs() int32 {
	if x != nil {
		return x.AckWaitInSecs
	}
	return 0
}

func (x *SubscriptionRequest) GetDurableName() string {
	if x != nil {
		return x.DurableName
	}
	return ""
}

func (x *SubscriptionRequest) GetStartPosition() StartPosition {
	if x != nil {
		return x.StartPosition
	}
	return StartPosition_NewOnly
}

func (x *SubscriptionRequest) GetStartSequence() uint64 {
	if x != nil {
		return x.StartSequence
	}
	return 0
}

func (x *SubscriptionRequest) GetStartTimeDelta() int64 {
	if x != nil {
		return x.StartTimeDelta
	}
	return 0
}

// Response for SubscriptionRequest and UnsubscribeRequests
type SubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckInbox      string                 `protobuf:"bytes,2,opt,name=ackInbox,proto3" json:"ackInbox,omitempty"` // ackInbox for sending acks
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`       // err string, empty/omitted if no error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *SubscriptionResponse) GetAckInbox() string {
	if x != nil {
		return x.AckInbox
	}
	return ""
}

func (x *SubscriptionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Protocol for a clients to unsubscribe. Will return a SubscriptionResponse
type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`       // ClientID
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`         // subject for the subscription
	Inbox         string                 `protobuf:"bytes,3,opt,name=inbox,proto3" json:"inbox,omitempty"`             // Inbox subject to identify subscription
	DurableName   string                 `protobuf:"bytes,4,opt,name=durableName,proto3" json:"durableName,omitempty"` // Optional durable name which survives client restarts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *UnsubscribeRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *UnsubscribeRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UnsubscribeRequest) GetInbox() string {
	if x != nil {
		return x.Inbox
	}
	return ""
}

func (x *UnsubscribeRequest) GetDurableName() string {
	if x != nil {
		return x.DurableName
	}
	return ""
}

// Protocol for a client to close a connection
type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"` // Client name provided to Connect() requests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *CloseRequest) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

// Response for CloseRequest
type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // err string, empty/omitted if no error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_type_streaming_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_api_envoy_type_streaming_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *CloseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_envoy_type_streaming_protocol_proto protoreflect.FileDescriptor

const file_api_envoy_type_streaming_protocol_proto_rawDesc = "" +
	"\n" +
	"'api/envoy/type/streaming/protocol.proto\x12\x02pb\"\x94\x01\n" +
	"\x06PubMsg\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12\x12\n" +
	"\x04guid\x18\x02 \x01(\tR\x04guid\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x14\n" +
	"\x05reply\x18\x04 \x01(\tR\x05reply\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x16\n" +
	"\x06sha256\x18\n" +
	" \x01(\fR\x06sha256\"2\n" +
	"\x06PubAck\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc0\x01\n" +
	"\bMsgProto\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05reply\x18\x03 \x01(\tR\x05reply\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12 \n" +
	"\vredelivered\x18\x06 \x01(\bR\vredelivered\x12\x14\n" +
	"\x05CRC32\x18\n" +
	" \x01(\rR\x05CRC32\";\n" +
	"\x03Ack\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"T\n" +
	"\x0eConnectRequest\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12&\n" +
	"\x0eheartbeatInbox\x18\x02 \x01(\tR\x0eheartbeatInbox\"\xfd\x01\n" +
	"\x0fConnectResponse\x12\x1c\n" +
	"\tpubPrefix\x18\x01 \x01(\tR\tpubPrefix\x12 \n" +
	"\vsubRequests\x18\x02 \x01(\tR\vsubRequests\x12$\n" +
	"\runsubRequests\x18\x03 \x01(\tR\runsubRequests\x12$\n" +
	"\rcloseRequests\x18\x04 \x01(\tR\rcloseRequests\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12*\n" +
	"\x10subCloseRequests\x18\x06 \x01(\tR\x10subCloseRequests\x12\x1c\n" +
	"\tpublicKey\x18d \x01(\tR\tpublicKey\"\xea\x02\n" +
	"\x13SubscriptionRequest\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06qGroup\x18\x03 \x01(\tR\x06qGroup\x12\x14\n" +
	"\x05inbox\x18\x04 \x01(\tR\x05inbox\x12 \n" +
	"\vmaxInFlight\x18\x05 \x01(\x05R\vmaxInFlight\x12$\n" +
	"\rackWaitInSecs\x18\x06 \x01(\x05R\rackWaitInSecs\x12 \n" +
	"\vdurableName\x18\a \x01(\tR\vdurableName\x127\n" +
	"\rstartPosition\x18\n" +
	" \x01(\x0e2\x11.pb.StartPositionR\rstartPosition\x12$\n" +
	"\rstartSequence\x18\v \x01(\x04R\rstartSequence\x12&\n" +
	"\x0estartTimeDelta\x18\f \x01(\x03R\x0estartTimeDelta\"H\n" +
	"\x14SubscriptionResponse\x12\x1a\n" +
	"\backInbox\x18\x02 \x01(\tR\backInbox\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x82\x01\n" +
	"\x12UnsubscribeRequest\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05inbox\x18\x03 \x01(\tR\x05inbox\x12 \n" +
	"\vdurableName\x18\x04 \x01(\tR\vdurableName\"*\n" +
	"\fCloseRequest\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\"%\n" +
	"\rCloseResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error*`\n" +
	"\rStartPosition\x12\v\n" +
	"\aNewOnly\x10\x00\x12\x10\n" +
	"\fLastReceived\x10\x01\x12\x12\n" +
	"\x0eTimeDeltaStart\x10\x02\x12\x11\n" +
	"\rSequenceStart\x10\x03\x12\t\n" +
	"\x05First\x10\x04B;Z9github.com/solo-io/envoy-gloo/go/type/streaming;streamingb\x06proto3"

var (
	file_api_envoy_type_streaming_protocol_proto_rawDescOnce sync.Once
	file_api_envoy_type_streaming_protocol_proto_rawDescData []byte
)

func file_api_envoy_type_streaming_protocol_proto_rawDescGZIP() []byte {
	file_api_envoy_type_streaming_protocol_proto_rawDescOnce.Do(func() {
		file_api_envoy_type_streaming_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_envoy_type_streaming_protocol_proto_rawDesc), len(file_api_envoy_type_streaming_protocol_proto_rawDesc)))
	})
	return file_api_envoy_type_streaming_protocol_proto_rawDescData
}

var file_api_envoy_type_streaming_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_envoy_type_streaming_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_envoy_type_streaming_protocol_proto_goTypes = []any{
	(StartPosition)(0),           // 0: pb.StartPosition
	(*PubMsg)(nil),               // 1: pb.PubMsg
	(*PubAck)(nil),               // 2: pb.PubAck
	(*MsgProto)(nil),             // 3: pb.MsgProto
	(*Ack)(nil),                  // 4: pb.Ack
	(*ConnectRequest)(nil),       // 5: pb.ConnectRequest
	(*ConnectResponse)(nil),      // 6: pb.ConnectResponse
	(*SubscriptionRequest)(nil),  // 7: pb.SubscriptionRequest
	(*SubscriptionResponse)(nil), // 8: pb.SubscriptionResponse
	(*UnsubscribeRequest)(nil),   // 9: pb.UnsubscribeRequest
	(*CloseRequest)(nil),         // 10: pb.CloseRequest
	(*CloseResponse)(nil),        // 11: pb.CloseResponse
}
var file_api_envoy_type_streaming_protocol_proto_depIdxs = []int32{
	0, // 0: pb.SubscriptionRequest.startPosition:type_name -> pb.StartPosition
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_envoy_type_streaming_protocol_proto_init() }
func file_api_envoy_type_streaming_protocol_proto_init() {
	if File_api_envoy_type_streaming_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_envoy_type_streaming_protocol_proto_rawDesc), len(file_api_envoy_type_streaming_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_envoy_type_streaming_protocol_proto_goTypes,
		DependencyIndexes: file_api_envoy_type_streaming_protocol_proto_depIdxs,
		EnumInfos:         file_api_envoy_type_streaming_protocol_proto_enumTypes,
		MessageInfos:      file_api_envoy_type_streaming_protocol_proto_msgTypes,
	}.Build()
	File_api_envoy_type_streaming_protocol_proto = out.File
	file_api_envoy_type_streaming_protocol_proto_goTypes = nil
	file_api_envoy_type_streaming_protocol_proto_depIdxs = nil
}
