# Configurable binary flags
label_flag(
    name = "envoy-binary",
    visibility = ["//visibility:public"],
    build_setting_default = "//source/exe:envoy-static",
)

label_flag(
    name = "envoy-binary-stripped",
    visibility = ["//visibility:public"],
    build_setting_default = "//source/exe:envoy-static.stripped",
)

label_flag(
    name = "envoy-dwarf",
    visibility = ["//visibility:public"],
    build_setting_default = "//source/exe:envoy-static.dwp",
)

