steps:
- name: 'envoyproxy/envoy-build-ubuntu:f94a38f62220a2b017878b790b6ea98a0f6c5f9c'
  id: 'gengo'
  args: ['make', 'check-gencode']
  volumes:
  - name: 'vol-build'
    path: '/build'
  env:
  - 'COMMIT_SHA=$COMMIT_SHA'
  - 'BAZEL_REMOTE_CACHE=https://storage.googleapis.com/envoy-build-cache-solo-io'
  - 'BUILD_TYPE=$_BUILD_TYPE'
  secretEnv:
  - 'GCP_SERVICE_ACCOUNT_KEY'

- name: 'envoyproxy/envoy-build-ubuntu:f94a38f62220a2b017878b790b6ea98a0f6c5f9c'
  id: 'do_ci'
  args: ['ci/do_ci.sh', 'release', '//test/extensions/...', '//test/common/...', '//test/integration/...']
  volumes:
  - name: 'vol-build'
    path: '/build'
  env:
  - 'COMMIT_SHA=$COMMIT_SHA'
  - 'BAZEL_REMOTE_CACHE=https://storage.googleapis.com/envoy-build-cache-solo-io'
  - 'BUILD_TYPE=$_BUILD_TYPE'
  secretEnv:
  - 'GCP_SERVICE_ACCOUNT_KEY'

- name: 'envoyproxy/envoy-build-ubuntu:41c5a05d708972d703661b702a63ef5060125c33'
  id: 'static_analysis'
  allowFailure: true
  args: ['ci/static_analysis.sh']
  volumes:
  - name: 'vol-build'
    path: '/build'
  env:
  - 'COMMIT_SHA=$COMMIT_SHA'
  - 'BAZEL_REMOTE_CACHE=https://storage.googleapis.com/envoy-build-cache-solo-io'
  - 'BUILD_TYPE=$_BUILD_TYPE'
  secretEnv:
  - 'GCP_SERVICE_ACCOUNT_KEY'

- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-release'
  entrypoint: 'bash'
  args: ['-c', 'docker login quay.io --username "solo-io+solobot" --password $$QUAY_IO_PASSWORD && cp linux/amd64/build_envoy_release_stripped/envoy ci/envoy.stripped && make docker-release']
  env:
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'COMMIT_SHA=$COMMIT_SHA'
  - 'BAZEL_REMOTE_CACHE=https://storage.googleapis.com/envoy-build-cache-solo-io'
  secretEnv:
    - 'QUAY_IO_PASSWORD'
    - 'GCP_SERVICE_ACCOUNT_KEY'
  volumes:
  - name: 'vol-build'
    path: '/build'

- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args:
  - '-ec'
  - |
    if [ -z "$$TAGGED_VERSION" ]; then exit 0; fi
    gsutil cp ./linux/amd64/build_envoy_release_stripped/envoy gs://solo-public-artifacts.solo.io/envoy/$${TAGGED_VERSION}/envoy.stripped
  id: 'save-tagged-version'
  env:
  - 'TAGGED_VERSION=$TAG_NAME'

options:
  pool:
    name: 'projects/solo-public/locations/us-central1/workerPools/envoy-gloo-runner'
timeout: 20000s

artifacts:
  objects:
    location: 'gs://solo-public-artifacts.solo.io/envoy/$COMMIT_SHA/'
    paths: ['linux/amd64/build_envoy_release/envoy']

tags:
  - "repo_envoy-gloo"
  # This tag can be used to filter for or out jobs which are spawned by the main job
  # submitted by build-bot. It's somewhat redundant as one could filter on `tags~^pr`
  # to achieve the same effect since that tag is added to main jobs by build-bot,
  # but this is somewhat less esoteric
  - "sub-job"

availableSecrets:
  inline:
   - kmsKeyName: projects/solo-public/locations/global/keyRings/build/cryptoKeys/build-key
     envMap:
       QUAY_IO_PASSWORD: 'CiQABlzmSRx5TcOqbldXa/d/+bkmAfpNAWa3PTS06WvuloZL+vASaQCCPGSGCogonVZVEUNx4G3YJtWi18gSuNx4PvLe08q8xAflTMFkjsyQirAOK3Y2oCvgYwiw/ITcuydjkpMjxDygFyENXS9FKFJoAXHlPQE5qidKr8xxmxF5ezhmjGB0gjyjXIIkbSEnBg=='
  secretManager:
    - versionName: projects/gloo-ee/secrets/envoy-build-cache-sa/versions/2
      env: 'GCP_SERVICE_ACCOUNT_KEY'
