// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/envoy/config/filter/http/aws_lambda/v2/aws_lambda.proto

package v2

import (
	v3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AWS Lambda contains the configuration necessary to perform transform regular
// http calls to AWS Lambda invocations.
type AWSLambdaPerRoute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the function
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The qualifier of the function (defaults to $LATEST if not specified)
	Qualifier string `protobuf:"bytes,2,opt,name=qualifier,proto3" json:"qualifier,omitempty"`
	// Invocation type - async or regular.
	Async bool `protobuf:"varint,3,opt,name=async,proto3" json:"async,omitempty"`
	// Optional default body if the body is empty. By default on default
	// body is used if the body empty, and an empty body will be sent upstream.
	EmptyBodyOverride *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=empty_body_override,json=emptyBodyOverride,proto3" json:"empty_body_override,omitempty"`
	// Deprecated. Use transformer_config to specify an AWS Lambda response transformer instead.
	// Unwrap responses as AWS ALB does.
	// Expects json lambda responses to construct response.
	// Intended to ease migration when previously using alb to invoke Lambdas.
	// When set on a route the filter will not stream data on the encoding step.
	// Defaults to false.
	//
	// Deprecated: Marked as deprecated in api/envoy/config/filter/http/aws_lambda/v2/aws_lambda.proto.
	UnwrapAsAlb bool `protobuf:"varint,5,opt,name=unwrap_as_alb,json=unwrapAsAlb,proto3" json:"unwrap_as_alb,omitempty"`
	// This is a transformer config, as defined in api.envoy.config.filter.http.transformation.v2
	// used to process response data.
	// This config cannot be configured simultaneously with unwrap_as_alb
	TransformerConfig *v3.TypedExtensionConfig `protobuf:"bytes,6,opt,name=transformer_config,json=transformerConfig,proto3" json:"transformer_config,omitempty"`
	// This is a transformer config, as defined in api.envoy.config.filter.http.transformation.v2
	// used to process request data.
	RequestTransformerConfig *v3.TypedExtensionConfig `protobuf:"bytes,7,opt,name=request_transformer_config,json=requestTransformerConfig,proto3" json:"request_transformer_config,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AWSLambdaPerRoute) Reset() {
	*x = AWSLambdaPerRoute{}
	mi := &file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSLambdaPerRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSLambdaPerRoute) ProtoMessage() {}

func (x *AWSLambdaPerRoute) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSLambdaPerRoute.ProtoReflect.Descriptor instead.
func (*AWSLambdaPerRoute) Descriptor() ([]byte, []int) {
	return file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescGZIP(), []int{0}
}

func (x *AWSLambdaPerRoute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AWSLambdaPerRoute) GetQualifier() string {
	if x != nil {
		return x.Qualifier
	}
	return ""
}

func (x *AWSLambdaPerRoute) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *AWSLambdaPerRoute) GetEmptyBodyOverride() *wrapperspb.StringValue {
	if x != nil {
		return x.EmptyBodyOverride
	}
	return nil
}

// Deprecated: Marked as deprecated in api/envoy/config/filter/http/aws_lambda/v2/aws_lambda.proto.
func (x *AWSLambdaPerRoute) GetUnwrapAsAlb() bool {
	if x != nil {
		return x.UnwrapAsAlb
	}
	return false
}

func (x *AWSLambdaPerRoute) GetTransformerConfig() *v3.TypedExtensionConfig {
	if x != nil {
		return x.TransformerConfig
	}
	return nil
}

func (x *AWSLambdaPerRoute) GetRequestTransformerConfig() *v3.TypedExtensionConfig {
	if x != nil {
		return x.RequestTransformerConfig
	}
	return nil
}

type AWSLambdaProtocolExtension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The host header for AWS this cluster
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// The region for this cluster
	Region string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// The access_key for AWS this cluster
	AccessKey string `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	// The secret_key for AWS this cluster
	SecretKey string `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// The session_token for AWS this cluster
	SessionToken string `protobuf:"bytes,5,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// The role_arn to use when generating credentials for the mounted projected SA token
	RoleArn string `protobuf:"bytes,6,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	// Optional override to disable role chaining;
	DisableRoleChaining bool `protobuf:"varint,7,opt,name=disable_role_chaining,json=disableRoleChaining,proto3" json:"disable_role_chaining,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AWSLambdaProtocolExtension) Reset() {
	*x = AWSLambdaProtocolExtension{}
	mi := &file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSLambdaProtocolExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSLambdaProtocolExtension) ProtoMessage() {}

func (x *AWSLambdaProtocolExtension) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSLambdaProtocolExtension.ProtoReflect.Descriptor instead.
func (*AWSLambdaProtocolExtension) Descriptor() ([]byte, []int) {
	return file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescGZIP(), []int{1}
}

func (x *AWSLambdaProtocolExtension) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AWSLambdaProtocolExtension) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AWSLambdaProtocolExtension) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *AWSLambdaProtocolExtension) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *AWSLambdaProtocolExtension) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AWSLambdaProtocolExtension) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *AWSLambdaProtocolExtension) GetDisableRoleChaining() bool {
	if x != nil {
		return x.DisableRoleChaining
	}
	return false
}

type AWSLambdaConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CredentialsFetcher:
	//
	//	*AWSLambdaConfig_UseDefaultCredentials
	//	*AWSLambdaConfig_ServiceAccountCredentials_
	CredentialsFetcher isAWSLambdaConfig_CredentialsFetcher `protobuf_oneof:"credentials_fetcher"`
	// Send downstream path and method as `x-envoy-original-path` and
	// `x-envoy-original-method` headers on the request to AWS lambda.
	// Defaults to false.
	PropagateOriginalRouting bool `protobuf:"varint,3,opt,name=propagate_original_routing,json=propagateOriginalRouting,proto3" json:"propagate_original_routing,omitempty"`
	// Sets cadence for refreshing credentials for Service Account.
	// Does nothing if Service account is not set.
	// Does not affect the default filewatch for service account only augments it.
	// Defaults to not refreshing on time period. Suggested is 15 minutes.
	CredentialRefreshDelay *durationpb.Duration `protobuf:"bytes,4,opt,name=credential_refresh_delay,json=credentialRefreshDelay,proto3" json:"credential_refresh_delay,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AWSLambdaConfig) Reset() {
	*x = AWSLambdaConfig{}
	mi := &file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSLambdaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSLambdaConfig) ProtoMessage() {}

func (x *AWSLambdaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSLambdaConfig.ProtoReflect.Descriptor instead.
func (*AWSLambdaConfig) Descriptor() ([]byte, []int) {
	return file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescGZIP(), []int{2}
}

func (x *AWSLambdaConfig) GetCredentialsFetcher() isAWSLambdaConfig_CredentialsFetcher {
	if x != nil {
		return x.CredentialsFetcher
	}
	return nil
}

func (x *AWSLambdaConfig) GetUseDefaultCredentials() *wrapperspb.BoolValue {
	if x != nil {
		if x, ok := x.CredentialsFetcher.(*AWSLambdaConfig_UseDefaultCredentials); ok {
			return x.UseDefaultCredentials
		}
	}
	return nil
}

func (x *AWSLambdaConfig) GetServiceAccountCredentials() *AWSLambdaConfig_ServiceAccountCredentials {
	if x != nil {
		if x, ok := x.CredentialsFetcher.(*AWSLambdaConfig_ServiceAccountCredentials_); ok {
			return x.ServiceAccountCredentials
		}
	}
	return nil
}

func (x *AWSLambdaConfig) GetPropagateOriginalRouting() bool {
	if x != nil {
		return x.PropagateOriginalRouting
	}
	return false
}

func (x *AWSLambdaConfig) GetCredentialRefreshDelay() *durationpb.Duration {
	if x != nil {
		return x.CredentialRefreshDelay
	}
	return nil
}

type isAWSLambdaConfig_CredentialsFetcher interface {
	isAWSLambdaConfig_CredentialsFetcher()
}

type AWSLambdaConfig_UseDefaultCredentials struct {
	// Use AWS default credentials chain to get credentials.
	// This will search environment variables, ECS metadata and instance metadata
	// to get the credentials. credentials will be rotated automatically.
	//
	// If credentials are provided on the cluster (using the
	// AWSLambdaProtocolExtension), it will override these credentials. This
	// defaults to false, but may change in the future to true.
	UseDefaultCredentials *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=use_default_credentials,json=useDefaultCredentials,proto3,oneof"`
}

type AWSLambdaConfig_ServiceAccountCredentials_ struct {
	// Use projected service account token, and role arn to create temporary
	// credentials with which to authenticate lambda requests.
	// This functionality is meant to work alongside EKS service account to IAM
	// binding functionality as described in the [AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).
	//
	// If the following environment values are not present, this option cannot be used.
	//  1. AWS_WEB_IDENTITY_TOKEN_FILE
	//  2. AWS_ROLE_ARN
	//
	// The role arn may also be specified in the `AWSLambdaProtocolExtension` on the cluster level,
	// to override the environment variable.
	ServiceAccountCredentials *AWSLambdaConfig_ServiceAccountCredentials `protobuf:"bytes,2,opt,name=service_account_credentials,json=serviceAccountCredentials,proto3,oneof"`
}

func (*AWSLambdaConfig_UseDefaultCredentials) isAWSLambdaConfig_CredentialsFetcher() {}

func (*AWSLambdaConfig_ServiceAccountCredentials_) isAWSLambdaConfig_CredentialsFetcher() {}

// In order to specify the aws sts endpoint, both the cluster and uri must be set.
// This is due to an envoy limitation which cannot infer the host or path from the cluster,
// and therefore must be explicitly specified via the uri
type AWSLambdaConfig_ServiceAccountCredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the envoy cluster which represents the desired aws sts endpoint
	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// The full uri of the aws sts endpoint
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// timeout for the request
	Timeout *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Region for the sts endpoint, defaults to us-east-1.
	// This must be an enabled region https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html
	// This should match the region specified in the uri.
	Region        string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AWSLambdaConfig_ServiceAccountCredentials) Reset() {
	*x = AWSLambdaConfig_ServiceAccountCredentials{}
	mi := &file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AWSLambdaConfig_ServiceAccountCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AWSLambdaConfig_ServiceAccountCredentials) ProtoMessage() {}

func (x *AWSLambdaConfig_ServiceAccountCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AWSLambdaConfig_ServiceAccountCredentials.ProtoReflect.Descriptor instead.
func (*AWSLambdaConfig_ServiceAccountCredentials) Descriptor() ([]byte, []int) {
	return file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AWSLambdaConfig_ServiceAccountCredentials) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *AWSLambdaConfig_ServiceAccountCredentials) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *AWSLambdaConfig_ServiceAccountCredentials) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *AWSLambdaConfig_ServiceAccountCredentials) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto protoreflect.FileDescriptor

const file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDesc = "" +
	"\n" +
	";api/envoy/config/filter/http/aws_lambda/v2/aws_lambda.proto\x12&envoy.config.filter.http.aws_lambda.v2\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x17validate/validate.proto\x1a$envoy/config/core/v3/extension.proto\"\x9f\x03\n" +
	"\x11AWSLambdaPerRoute\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02 \x01R\x04name\x12\x1c\n" +
	"\tqualifier\x18\x02 \x01(\tR\tqualifier\x12\x14\n" +
	"\x05async\x18\x03 \x01(\bR\x05async\x12L\n" +
	"\x13empty_body_override\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x11emptyBodyOverride\x12&\n" +
	"\runwrap_as_alb\x18\x05 \x01(\bB\x02\x18\x01R\vunwrapAsAlb\x12Y\n" +
	"\x12transformer_config\x18\x06 \x01(\v2*.envoy.config.core.v3.TypedExtensionConfigR\x11transformerConfig\x12h\n" +
	"\x1arequest_transformer_config\x18\a \x01(\v2*.envoy.config.core.v3.TypedExtensionConfigR\x18requestTransformerConfig\"\x8c\x02\n" +
	"\x1aAWSLambdaProtocolExtension\x12\x1b\n" +
	"\x04host\x18\x01 \x01(\tB\a\xfaB\x04r\x02 \x01R\x04host\x12\x1f\n" +
	"\x06region\x18\x02 \x01(\tB\a\xfaB\x04r\x02 \x01R\x06region\x12\x1d\n" +
	"\n" +
	"access_key\x18\x03 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\x12#\n" +
	"\rsession_token\x18\x05 \x01(\tR\fsessionToken\x12\x19\n" +
	"\brole_arn\x18\x06 \x01(\tR\aroleArn\x122\n" +
	"\x15disable_role_chaining\x18\a \x01(\bR\x13disableRoleChaining\"\xd0\x04\n" +
	"\x0fAWSLambdaConfig\x12T\n" +
	"\x17use_default_credentials\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueH\x00R\x15useDefaultCredentials\x12\x93\x01\n" +
	"\x1bservice_account_credentials\x18\x02 \x01(\v2Q.envoy.config.filter.http.aws_lambda.v2.AWSLambdaConfig.ServiceAccountCredentialsH\x00R\x19serviceAccountCredentials\x12<\n" +
	"\x1apropagate_original_routing\x18\x03 \x01(\bR\x18propagateOriginalRouting\x12S\n" +
	"\x18credential_refresh_delay\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x16credentialRefreshDelay\x1a\xa6\x01\n" +
	"\x19ServiceAccountCredentials\x12!\n" +
	"\acluster\x18\x01 \x01(\tB\a\xfaB\x04r\x02 \x01R\acluster\x12\x19\n" +
	"\x03uri\x18\x02 \x01(\tB\a\xfaB\x04r\x02 \x01R\x03uri\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06regionB\x15\n" +
	"\x13credentials_fetcherB\x8e\x01\n" +
	"4io.envoyproxy.envoy.config.filter.http.aws_lambda.v2B\x0eAwsLambdaProtoP\x01ZDgithub.com/solo-io/envoy-gloo/go/config/filter/http/aws_lambda/v2;v2b\x06proto3"

var (
	file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescOnce sync.Once
	file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescData []byte
)

func file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescGZIP() []byte {
	file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescOnce.Do(func() {
		file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDesc), len(file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDesc)))
	})
	return file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDescData
}

var file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_goTypes = []any{
	(*AWSLambdaPerRoute)(nil),                         // 0: envoy.config.filter.http.aws_lambda.v2.AWSLambdaPerRoute
	(*AWSLambdaProtocolExtension)(nil),                // 1: envoy.config.filter.http.aws_lambda.v2.AWSLambdaProtocolExtension
	(*AWSLambdaConfig)(nil),                           // 2: envoy.config.filter.http.aws_lambda.v2.AWSLambdaConfig
	(*AWSLambdaConfig_ServiceAccountCredentials)(nil), // 3: envoy.config.filter.http.aws_lambda.v2.AWSLambdaConfig.ServiceAccountCredentials
	(*wrapperspb.StringValue)(nil),                    // 4: google.protobuf.StringValue
	(*v3.TypedExtensionConfig)(nil),                   // 5: envoy.config.core.v3.TypedExtensionConfig
	(*wrapperspb.BoolValue)(nil),                      // 6: google.protobuf.BoolValue
	(*durationpb.Duration)(nil),                       // 7: google.protobuf.Duration
}
var file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_depIdxs = []int32{
	4, // 0: envoy.config.filter.http.aws_lambda.v2.AWSLambdaPerRoute.empty_body_override:type_name -> google.protobuf.StringValue
	5, // 1: envoy.config.filter.http.aws_lambda.v2.AWSLambdaPerRoute.transformer_config:type_name -> envoy.config.core.v3.TypedExtensionConfig
	5, // 2: envoy.config.filter.http.aws_lambda.v2.AWSLambdaPerRoute.request_transformer_config:type_name -> envoy.config.core.v3.TypedExtensionConfig
	6, // 3: envoy.config.filter.http.aws_lambda.v2.AWSLambdaConfig.use_default_credentials:type_name -> google.protobuf.BoolValue
	3, // 4: envoy.config.filter.http.aws_lambda.v2.AWSLambdaConfig.service_account_credentials:type_name -> envoy.config.filter.http.aws_lambda.v2.AWSLambdaConfig.ServiceAccountCredentials
	7, // 5: envoy.config.filter.http.aws_lambda.v2.AWSLambdaConfig.credential_refresh_delay:type_name -> google.protobuf.Duration
	7, // 6: envoy.config.filter.http.aws_lambda.v2.AWSLambdaConfig.ServiceAccountCredentials.timeout:type_name -> google.protobuf.Duration
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_init() }
func file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_init() {
	if File_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto != nil {
		return
	}
	file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes[2].OneofWrappers = []any{
		(*AWSLambdaConfig_UseDefaultCredentials)(nil),
		(*AWSLambdaConfig_ServiceAccountCredentials_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDesc), len(file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_goTypes,
		DependencyIndexes: file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_depIdxs,
		MessageInfos:      file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_msgTypes,
	}.Build()
	File_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto = out.File
	file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_goTypes = nil
	file_api_envoy_config_filter_http_aws_lambda_v2_aws_lambda_proto_depIdxs = nil
}
