name: static-analysis

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  static-analysis:
    name: static-analysis
    runs-on: ubuntu-20.04-8core
    container: envoyproxy/envoy-build-ubuntu:f94a38f62220a2b017878b790b6ea98a0f6c5f9c
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy-gloo/envoy-gloo
    - name: Run static analysis
      run: ci/static_analysis.sh
    - name: Archive static analysis results
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: static-analysis-report
        path: linux/amd64/analysis/scan-build-*/
