name: static-analysis

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  static-analysis:
    name: static-analysis
    runs-on: ubuntu-20.04-8core
    container: gcr.io/solo-public/envoy-build-ubuntu:0.4.25
    steps:
    - uses: actions/checkout@v3
    - name: Add safe directory
      run: git config --global --add safe.directory /__w/envoy-gloo/envoy-gloo
    - name: Run static analysis
      run: ci/static_analysis.sh
    - name: Archive static analysis results
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v3
      with:
        name: static-analysis-report
        path: linux/amd64/analysis/scan-build-*/
